<template>
  <div class="about">
    <h3>I. There are 2 modes: database mode and csv mode.</h3>
    <div>1. Csv mode:
      Click choose file button and choose csv file. It will load all records from the csv file.
      In Csv mode data was shown in the table will be imported.</div>
    <div>2. Database mode:
      Click the database mode button will clear the employee table
      and load employees from the database.
      In Database mode data was shown in the table will be updated.</div>
    <div>3. User can edit in both modes before import/update.</div>
    <div>4. In database mode: only the edited row was updated,
      if there is no updated row then the update button will not be shown.</div>
    <h3>II. Data validation.</h3>
    <div>1. Field dateOfBirth must be date type when posted to the server.
      The other field is string type.</div>
    <div>2. There is no unique field except the Id field which is generated by the database.
      That means: empId, firstName, lastName, and dateOfBirth can be duplicated.</div>
    <div>3. empId, firstName, lastName and dateOfBirth can be empty/null.</div>
    <h3>III. Upload limitation.</h3>
    <div>1. Import API support only 200MB of the body size of the request.
      So, if the body size of the request must be smaller than 200MB.</div>
    <div>2. Update API support only 30MB of the body size of the request.
      So, if the body size of the request must be smaller than 3MB.</div>
    <div>3. To handle bigger data we need to slice the data and call API multiple times,
      but this feature was not implemented in the front end.
    </div>
    <div>4. It's take around 1 - 2 mins to import 1M employees in local environment.
    </div>
  </div>
</template>
<style scoped lang="scss">
div {
  text-align: left;
  margin-left: 10px;
}
</style>
